name: Build & Deploy to Sandbox

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Configure Maven settings
        run: mkdir -p ~/.m2 && cp testapi/.m2/settings.xml ~/.m2/settings.xml

      - name: Build with Maven
        run: mvn -B package
        working-directory: testapi

      # - name: Stamp artifact file name with commit hash
      #   run: |
      #     artifactName1=$(ls target/*.jar | head -1)
      #     commitHash=$(git rev-parse --short "$GITHUB_SHA")
      #     artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
      #     mv $artifactName1 $artifactName2
      #   working-directory: testapi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: testapi/target/*.jar

      - name: List target contents
        run: ls -l target
        working-directory: testapi

      - name: Deploy to CloudHub 2.0
        run: mvn deploy -Dmule.env=${{ secrets.dev }} -DskipExchange=true
        working-directory: testapi
        env:
          anypoint.username: ${{ secrets.ANYPOINT_USERNAME }}
          anypoint.password: ${{ secrets.ANYPOINT_PASSWORD }}
