# This is a basic workflow to help you get started with Actions

name: Build & Deploy to Sandbox

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml')}}
          restore-keys: |
             ${{ runner.os }}-maven-

      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Print effective-settings (optional)
        run: mvn help:effective-settings --settings .github/settings.xml
        #working-directory: testapi # Ensure this runs from the correct directory

      - name: Build with Maven
        run: mvn -B package --file pom.xml --settings .github/settings.xml
        #working-directory: testapi # Assumes pom.xml #is in a 'testapi' subdirectory

      - name: Stamp artifact file name with commit hash
        run: |
          artifactName1=$(ls target/*.jar | head -1)
          commitHash=$(git rev-parse --short "$GITHUB_SHA")
          artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash.jar/g")
          mv "$artifactName1" "$artifactName2" # Added quotes for robustness
        working-directory: testapi

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
            name: artifacts
            path: target/*.jar

      